spring:
  application:
    name: twofaang

  datasource:
    url: jdbc:mariadb://121.170.161.72:3306/twofaang
    username: admin
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  # oauth2
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: ${client-id-naver}
            client-secret: ${client-secret-naver}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope: name, email
          google:
            client-name: google
            client-id: ${client-id-google}
            client-secret: ${client-secret-google}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: profile, email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  jwt:
    secret: twofaangxnvkdgksdlfkjweriowelkjsdflkjsdfkljwelrmknslkcv32948723kwelknsdlknv

logging:
  level:
    org:
      springframework:
        web: DEBUG
    hibernate: DEBUG
